! Generated by cart. DO NOT EDIT
program main
    implicit none

    if (.not.run()) stop 1
contains
    function run() result(passed)
        use add_hanging_indentation_test, only: &
                add_hanging_indentation_add_hanging_indentation => &
                    test_add_hanging_indentation
        use format_hanging_indented_test, only: &
                format_hanging_indented_format_hanging_indented => &
                    test_format_hanging_indented
        use indent_test, only: &
                indent_indent => &
                    test_indent
        use is_infinity_test, only: &
                is_infinity_is_infinity => &
                    test_is_infinity
        use is_nan_test, only: &
                is_nan_is_nan => &
                    test_is_nan
        use is_zero_test, only: &
                is_zero_is_zero => &
                    test_is_zero
        use join_test, only: &
                join_join => &
                    test_join
        use read_file_lines_test, only: &
                read_file_lines_read_file_lines => &
                    test_read_file_lines
        use read_file_test, only: &
                read_file_read_file => &
                    test_read_file
        use split_at_test, only: &
                split_at_split_at => &
                    test_split_at
        use starts_with_test, only: &
                starts_with_starts_with => &
                    test_starts_with
        use to_string_test, only: &
                to_string_to_string_for_doubles => &
                    test_to_string_for_doubles, &
                to_string_to_string_for_integers => &
                    test_to_string_for_integers
        use veggies, only: test_item_t, test_that, run_tests



        logical :: passed

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(13)

        individual_tests(1) = add_hanging_indentation_add_hanging_indentation()
        individual_tests(2) = format_hanging_indented_format_hanging_indented()
        individual_tests(3) = indent_indent()
        individual_tests(4) = is_infinity_is_infinity()
        individual_tests(5) = is_nan_is_nan()
        individual_tests(6) = is_zero_is_zero()
        individual_tests(7) = join_join()
        individual_tests(8) = read_file_lines_read_file_lines()
        individual_tests(9) = read_file_read_file()
        individual_tests(10) = split_at_split_at()
        individual_tests(11) = starts_with_starts_with()
        individual_tests(12) = to_string_to_string_for_doubles()
        individual_tests(13) = to_string_to_string_for_integers()
        tests = test_that(individual_tests)


        passed = run_tests(tests)

    end function
end program
