image: registry.gitlab.com/everythingfunctional/dockerfpm

variables:
    GIT_SUBMODULE_STRATEGY: normal

test:
  script:
    - fpm test \
      --flag '-Wall' \
      --flag '-Wextra' \
      --flag '-Wimplicit-interface' \
      --flag '-Werror' \
      --flag '-fPIC' \
      --flag '-g3' \
      --flag '-fbounds-check' \
      --flag '-fcheck-array-temporaries' \
      --flag '-fbacktrace' \
      --flag '-std=f2018' \
      --flag '-fcheck=all' #\ TODO: run with valgrind once gfortran memory leaks have been fixed
      #--runner "valgrind --leak-check=full --error-exitcode=1"
