name = "strff"

[dependencies]
iso_varying_string = { git = "https://gitlab.com/everythingfunctional/iso_varying_string.git", branch = "MigrateToFpm" }

[dev-dependencies]
vegetables = { git = "https://gitlab.com/everythingfunctional/vegetables.git", branch = "MigrateToFpm" }
